version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t docker-app:latest .
      - docker tag docker-app:latest 247149228486.dkr.ecr.us-west-2.amazonaws.com/docker-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image..
      # Push the image to ECR.
      - docker push 247149228486.dkr.ecr.us-west-2.amazonaws.com/docker-app:latest
      - echo Completed pushing Docker image. Deploying Docker image to AWS Fargate on `date`
      # Create a artifacts file that contains the name and location of the image
      # pushed to ECR. This will be used by AWS CodePipeline to automate
      # deployment of this specific container to Amazon ECS.
      - printf '[{"name":"docker-app","imageUri":"%s"}]' 247149228486.dkr.ecr.us-west-2.amazonaws.com/docker-app:latest > Dockerrun.aws.json
artifacts:
  files:
    - Dockerrun.aws.json
