version: 0.2

phases:
  pre_build:
    commands:
      - echo start pre_build ...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t sujithes/docker-react -f Dockerfile.dev .
  post_build:
    commands:
      - echo Build started on `date`
      - docker run sujithes/docker-react yarn test -- --coverage
      - echo build completed on `date`
artifacts:
  # Indicate that the created imagedefinitions.json file created on the previous
  # line is to be referenceable as an artifact of the build execution job.
  files: imagedefinitions.json
